export const REQUEST_GAME = 'REQUEST_GAME';
export const RECEIVE_GAMES = 'RECEIVE_GAMES';


export const FETCH_GAMES_BEGIN = 'FETCH_GAMES_BEGIN';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
